const art = (name) => `/images/${name}.jpg`;

export const categories = [
  { name: "Serums", slug: "serums", image: art("serum") },
  { name: "Moisturizers", slug: "moisturizers", image: art("cream") },
  { name: "Cleansers", slug: "cleansers", image: art("cleanser") },
  { name: "SPF", slug: "spf", image: art("spf") },
  { name: "Sets", slug: "sets", image: art("set") },
  { name: "Body", slug: "body", image: art("body") },
];

export const catalog = [
  {
    name: "Luminous Peptide Serum",
    slug: "luminous-peptide-serum",
    subtitle: "Peptides · niacinamide",
    price: 48,
    comparePrice: 68,
    category: "serums",
    badge: "Best seller",
    bestseller: true,
    featured: true,
    sizes: ["30 ml", "50 ml"],
    rating: 4.9,
    reviewCount: 186,
    stock: 42,
    image: art("serum"),
    hoverImage: art("drops"),
    description:
      "A weightless daily serum that leaves skin looking smoother, clearer, and quietly lit. Peptides and niacinamide support a more even, rested complexion.",
    details:
      "Pressed in small batches. The watery texture layers under moisturizer and sits well under makeup. Suitable for most skin, including skin that feels reactive.",
    ingredients:
      "Aqua, niacinamide, glycerin, palmitoyl tripeptide-1, panthenol, hyaluronic acid, allantoin, rosewater.",
    howTo: "After cleansing, press four drops over the face and neck. Follow with Cloud Veil Moisturizer.",
    reviews: [
      { name: "Leila K.", stars: 5, text: "My skin looks glazed by the third morning. It never pills under tint." },
      { name: "Nora S.", stars: 5, text: "I retired two serums for this. Quiet, and it actually shows." },
    ],
  },
  {
    name: "Cloud Veil Moisturizer",
    slug: "cloud-veil-moisturizer",
    subtitle: "Ceramides · squalane",
    price: 42,
    comparePrice: 58,
    category: "moisturizers",
    badge: "Best seller",
    bestseller: true,
    featured: true,
    sizes: ["50 ml"],
    rating: 4.8,
    reviewCount: 143,
    stock: 36,
    image: art("cream"),
    hoverImage: art("eye"),
    description:
      "A cushiony cream that seals in water and leaves a soft-focus finish. Ceramides comfort the barrier without a heavy film.",
    details: "Rich enough for dry rooms and air travel, sheer enough for humid mornings. Fragrance-light, with a faint clean musk.",
    ingredients: "Squalane, ceramide NP, shea butter, glycerin, centella asiatica, cholesterol, vitamin E.",
    howTo: "Warm a pearl of cream between the fingers and press over serum, morning and night.",
    reviews: [
      { name: "Maya R.", stars: 5, text: "The finish is satin, not shiny. My cheeks stopped feeling tight." },
      { name: "Hana V.", stars: 4, text: "Beautiful texture. A little goes a long way on combination skin." },
    ],
  },
  {
    name: "Rosewater Milk Cleanser",
    slug: "rosewater-milk-cleanser",
    subtitle: "Rose · oat milk",
    price: 28,
    comparePrice: null,
    category: "cleansers",
    badge: "",
    bestseller: false,
    featured: true,
    sizes: ["150 ml"],
    rating: 4.7,
    reviewCount: 98,
    stock: 50,
    image: art("cleanser"),
    hoverImage: art("polish"),
    description:
      "A milky cleanser that melts sunscreen and the day without stripping. Skin feels cushioned, never squeaky.",
    details: "Non-foaming. Rinses clean and plays nicely with the rest of the ritual. The rose note is soft, not perfumey.",
    ingredients: "Rosewater, oat lipids, glycerin, coco-glucoside, panthenol, chamomile extract.",
    howTo: "Massage onto dry skin, emulsify with water, and rinse. Use morning and evening.",
    reviews: [
      { name: "Sara A.", stars: 5, text: "The only cleanser that does not leave my face feeling papery." },
    ],
  },
  {
    name: "Daily Mineral Veil SPF 50",
    slug: "daily-mineral-veil-spf-50",
    subtitle: "Zinc · glow finish",
    price: 36,
    comparePrice: 48,
    category: "spf",
    badge: "Sale",
    bestseller: true,
    featured: false,
    sizes: ["40 ml"],
    rating: 4.6,
    reviewCount: 121,
    stock: 28,
    image: art("spf"),
    hoverImage: art("serum"),
    description:
      "A mineral screen with a soft luminous finish, not a white cast. Wear it as the last step of the morning ritual.",
    details: "Broad spectrum SPF 50. Sits well under makeup after a minute of settling. Water resistant for light city days.",
    ingredients: "Zinc oxide, squalane, tinted iron oxides, bisabolol, vitamin E, sunflower seed oil.",
    howTo: "Apply two fingers' length as the final morning step. Reapply when you are out for long hours.",
    reviews: [
      { name: "Iman F.", stars: 5, text: "No chalkiness on medium skin. It looks like a soft tint." },
    ],
  },
  {
    name: "Midnight Repair Oil",
    slug: "midnight-repair-oil",
    subtitle: "Bakuchiol · sea buckthorn",
    price: 54,
    comparePrice: null,
    category: "serums",
    badge: "Night",
    bestseller: false,
    featured: true,
    sizes: ["30 ml"],
    rating: 4.8,
    reviewCount: 76,
    stock: 22,
    image: art("oil"),
    hoverImage: art("serum"),
    description:
      "Three drops at night for skin that wakes up looking rested. A dry oil, not a greasy veil.",
    details: "Bakuchiol offers a gentler alternative path to smoother-looking skin. Use on evenings you skip stronger treatments.",
    ingredients: "Squalane, bakuchiol, sea buckthorn oil, rosehip, bisabolol, rosemary extract.",
    howTo: "After serum, press three drops over the face. Skip if you prefer a matte finish.",
    reviews: [
      { name: "Priya D.", stars: 5, text: "My night cream felt heavy until I switched to this oil." },
    ],
  },
  {
    name: "Silk Barrier Cream",
    slug: "silk-barrier-cream",
    subtitle: "Centella · cholesterol",
    price: 46,
    comparePrice: null,
    category: "moisturizers",
    badge: "",
    bestseller: false,
    featured: false,
    sizes: ["50 ml"],
    rating: 4.9,
    reviewCount: 64,
    stock: 19,
    image: art("cream"),
    hoverImage: art("body"),
    description:
      "A recovery cream for days when skin feels warm, tight, or over-exfoliated. Comfort first, glow second.",
    details: "The texture is dense and calming. Many clients keep a jar for travel and air-conditioned offices.",
    ingredients: "Centella asiatica, cholesterol, fatty acids, shea, madecassoside, allantoin.",
    howTo: "Use as the last step at night, or whenever skin asks for a pause.",
    reviews: [
      { name: "Elena M.", stars: 5, text: "Calmed a windburned weekend in two nights." },
    ],
  },
  {
    name: "Gentle Enzyme Polish",
    slug: "gentle-enzyme-polish",
    subtitle: "Papaya · rice",
    price: 32,
    comparePrice: null,
    category: "cleansers",
    badge: "",
    bestseller: false,
    featured: false,
    sizes: ["60 ml"],
    rating: 4.5,
    reviewCount: 54,
    stock: 33,
    image: art("polish"),
    hoverImage: art("cleanser"),
    description:
      "A twice-weekly polish that loosens dullness without beads or scratch. Skin looks clearer, not scoured.",
    details: "Enzymes do the work while rice powder gives a very soft slip. Rinse before the mask sets fully.",
    ingredients: "Papaya enzyme, rice powder, kaolin, glycerin, aloe, chamomile.",
    howTo: "On clean skin, massage for one minute, leave for three, then rinse. Use twice a week.",
    reviews: [
      { name: "Jade P.", stars: 4, text: "Softer than a scrub. My makeup sits better the next day." },
    ],
  },
  {
    name: "Soft Focus Eye Cream",
    slug: "soft-focus-eye-cream",
    subtitle: "Caffeine · peptides",
    price: 40,
    comparePrice: 52,
    category: "moisturizers",
    badge: "Sale",
    bestseller: true,
    featured: false,
    sizes: ["15 ml"],
    rating: 4.7,
    reviewCount: 88,
    stock: 27,
    image: art("eye"),
    hoverImage: art("cream"),
    description:
      "A cooling cream for the eye area that softens the look of late nights. Light enough to wear under concealer.",
    details: "The metal-free tube keeps the texture cool. Pat, never rub.",
    ingredients: "Caffeine, peptide complex, niacinamide, shea, cucumber extract, vitamin E.",
    howTo: "Morning and night, tap a grain of rice amount under each eye.",
    reviews: [
      { name: "Amira L.", stars: 5, text: "Looks smoother by lunch. No milia, no fragrance sting." },
    ],
  },
  {
    name: "The Morning Ritual Set",
    slug: "the-morning-ritual-set",
    subtitle: "Cleanse · treat · veil",
    price: 89,
    comparePrice: 120,
    category: "sets",
    badge: "Save 26%",
    bestseller: true,
    featured: true,
    sizes: ["Full set"],
    rating: 5,
    reviewCount: 41,
    stock: 14,
    image: art("set"),
    hoverImage: art("serum"),
    description:
      "The three morning steps in one box: Rosewater Milk Cleanser, Luminous Peptide Serum, and Daily Mineral Veil.",
    details: "A considered introduction to the house. The set is priced below the three formulas bought separately.",
    ingredients: "See each formula. Packaged in a recyclable cream box with a ritual card.",
    howTo: "Cleanse, press serum, then finish with SPF. Full method is printed on the enclosed card.",
    reviews: [
      { name: "Christina W.", stars: 5, text: "I bought this as a gift and then ordered a second for myself." },
    ],
  },
  {
    name: "Cashmere Body Lotion",
    slug: "cashmere-body-lotion",
    subtitle: "Vanilla · shea",
    price: 34,
    comparePrice: null,
    category: "body",
    badge: "",
    bestseller: false,
    featured: false,
    sizes: ["200 ml"],
    rating: 4.8,
    reviewCount: 70,
    stock: 40,
    image: art("body"),
    hoverImage: art("cream"),
    description:
      "A fast-absorbing body lotion with the feel of a light cashmere layer. Skin looks smooth, never coated.",
    details: "The vanilla is dry and soft, closer to clean skin than dessert. A favorite after a shower.",
    ingredients: "Shea butter, glycerin, sweet almond, vanilla CO2, vitamin E, allantoin.",
    howTo: "Smooth over damp skin. Concentrate on shoulders, elbows, and legs.",
    reviews: [
      { name: "Farah N.", stars: 5, text: "Sinks in before I get dressed. The scent is very quiet." },
    ],
  },
  {
    name: "Dawn Glow Drops",
    slug: "dawn-glow-drops",
    subtitle: "Vitamin C · licorice",
    price: 38,
    comparePrice: null,
    category: "serums",
    badge: "New",
    bestseller: false,
    featured: true,
    sizes: ["30 ml"],
    rating: 4.6,
    reviewCount: 39,
    stock: 25,
    image: art("drops"),
    hoverImage: art("serum"),
    description:
      "A stable vitamin C treatment for a brighter look over time. Licorice root keeps the finish even.",
    details: "Amber glass protects the formula. Use in the morning under SPF.",
    ingredients: "Ascorbyl glucoside, licorice root, ferulic acid, glycerin, panthenol, vitamin E.",
    howTo: "Apply three drops before moisturizer. Always follow with Daily Mineral Veil.",
    reviews: [
      { name: "Yasmin T.", stars: 4, text: "Brighter at week two. No sticky cast." },
    ],
  },
  {
    name: "Botanical Hair Elixir",
    slug: "botanical-hair-elixir",
    subtitle: "Argan · camellia",
    price: 30,
    comparePrice: null,
    category: "hair",
    badge: "",
    bestseller: false,
    featured: false,
    sizes: ["50 ml"],
    rating: 4.7,
    reviewCount: 58,
    stock: 31,
    image: art("oil"),
    hoverImage: art("drops"),
    description:
      "A featherweight oil for ends and the occasional scalp massage. Hair looks polished, not wet.",
    details: "Works on waves and straight hair. One pump is enough for shoulder length.",
    ingredients: "Argan, camellia, broccolini seed oil, vitamin E, rosemary leaf.",
    howTo: "Warm one pump in the palms and smooth over mid-lengths and ends.",
    reviews: [
      { name: "Lina G.", stars: 5, text: "The shine is real and my silk pillowcase stays clean." },
    ],
  },
];

export function findProduct(slug) {
  return catalog.find((product) => product.slug === slug) || null;
}
